# docker-compose.yaml
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ppserver
      POSTGRES_PASSWORD: ppserver
      POSTGRES_DB: pp_db